name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        java: [17, 21, 25]
        platform: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v7
      with:
        lfs: true

    - uses: actions/cache@v6
      with:
        path: |
          ~/.sbt
          ~/.m2
          ~/.ivy2
          ~/.cache
        key: ${{ runner.os }}-build-${{ hashFiles('build.sbt', 'project/**') }}

    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Set up sbt
      uses: sbt/setup-sbt@v1

    - name: Check formatting
      run: sbt -mem 3000 scalafmtCheckAll
      if: matrix.java == 21

    - name: Run tests
      run: sbt -mem 3000 "+test"
